#!/usr/bin/env python3
"""
V22 EN prompt generator for ALL image-less SKUs.

Outputs a single text file with prompts in v22-test format:
  [HERO] / [DETAIL] / [VARIETY-A or VARIETY-C] / [MULTI-ANGLE]
for each SKU (4 prompts per SKU).

Skips: WI-001, PB-001 (already manually generated by user on 8/22).
Output: F:\\zprintpro-nextjs\\.hermes\\k3-inbox\\v22-prompts-all-en.txt
"""
import json
import re
import sys
from pathlib import Path

SKU_DATA_FILE = Path(r'F:\zprintpro-nextjs\.hermes\k3-inbox\sku-data.json')
OUTPUT_FILE = Path(r'F:\zprintpro-nextjs\.hermes\k3-inbox\v22-prompts-all-en.txt')

# Per-category US-market prompts config.
# Each entry: audience / scene / color_palette / seo_context
CATEGORY_CONFIG = {
    'stickers': {
        'audience': 'US small businesses, crafters, and product brands ordering custom stickers for packaging, product labels, laptop/ Hydro Flask decals, and event giveaways; they need durable, sharp-printed, brand-faithful stickers that survive daily use.',
        'scene': "A US craft fair booth or small-business packaging table - stickers on Hydro Flask bottles, laptops, mailers and product wraps, natural daylight, clean modern studio background.",
        'color_palette': 'brand-specific accents on neutral whites and warm wood tones.',
        'seo_context': 'custom sticker printing, vinyl stickers, die-cut stickers, waterproof stickers, product label stickers.',
    },
    'flyers': {
        'audience': 'US retail shops, restaurants, real-estate agents, event organizers and trade-show exhibitors ordering flyers and leaflets for promotions, menus, open houses and grand openings; they need crisp, on-brand flyers that drive foot traffic.',
        'scene': "An American retail storefront window display or trade-show booth - flyers stacked, fanned, hand-distributed, natural daylight, clean urban retail background.",
        'color_palette': 'brand-forward color scheme with strong typographic contrast.',
        'seo_context': 'flyer printing, leaflet printing, custom flyers, A4 flyers, marketing flyers.',
    },
    'packaging': {
        'audience': 'US beauty, skincare, jewelry, electronics and gift brands ordering custom rigid gift boxes, magnetic boxes, drawer boxes and lift-off-lid boxes for product launch and unboxing; they need premium feel and brand-true colors.',
        'scene': "An American boutique display shelf or unboxing flat-lay - gift boxes opened, magnetic flaps lifted, ribbon bows tied, soft studio lighting, clean white/neutral marble or kraft backdrop.",
        'color_palette': 'premium neutrals (ivory, charcoal, deep green, navy) with metallic gold or rose-gold accents.',
        'seo_context': 'custom packaging boxes, gift boxes, rigid boxes, magnetic closure boxes, premium packaging.',
    },
    'paper-bags': {
        'audience': 'US boutiques, food brands and eco-conscious retailers ordering custom paper bags; they need sturdy, branded and sustainable-looking bags.',
        'scene': "An American boutique storefront or farmers-market stall - bags hanging or held, natural daylight, clean retail background.",
        'color_palette': 'kraft brown, white, natural tones, minimal brand colors.',
        'seo_context': 'paper bag printing, kraft paper bags, custom gift bags, eco paper bags, handle bag printing.',
    },
    'posters': {
        'audience': 'US event organizers, retail stores, restaurants, art shows and exhibition hosts ordering posters for storefront windows, in-store displays, and trade-show backdrops; they need vibrant large-format prints.',
        'scene': "An American urban storefront window or gallery wall - posters mounted, framed, or hung in a row, daylight or gallery lighting, clean urban background.",
        'color_palette': 'bold saturated colors on white or dark contrast backgrounds.',
        'seo_context': 'poster printing, A2 posters, large-format posters, exhibition posters, custom posters.',
    },
    'books': {
        'audience': 'US publishers, photographers, designers, brand marketers and self-publishers ordering catalogs, photo books, lookbooks, and exhibition books; they need offset-quality color and durable binding.',
        'scene': "An American design studio or coffee-table setting - books stacked, fanned, open to a spread, natural daylight, modern minimalist interior.",
        'color_palette': 'paper white and ivory with deep accent colors from cover design.',
        'seo_context': 'book printing, catalog printing, photo book printing, lookbook printing, perfect bound books.',
    },
    'educational': {
        'audience': 'US K-12 schools, tutoring centers, training academies and homeschool parents ordering exercise books, workbooks, and school text materials; they need durable paper and child-safe finishes.',
        'scene': "An American elementary classroom or study desk - exercise books open with pencil and ruler, bright classroom lighting, warm wood desk.",
        'color_palette': 'school-friendly primary colors and warm wood tones.',
        'seo_context': 'exercise book printing, school workbook printing, custom notebooks, educational printing, K-12 supplies.',
    },
    'menus': {
        'audience': 'US restaurants, cafes, izakayas, hotel F&B and cha chaan teng operators ordering printed menus (paper and PVC); they need durable, easy-clean, on-brand menus.',
        'scene': "An American restaurant table or bar counter - menus propped, fanned or held, ambient restaurant lighting, warm wood and brick interior.",
        'color_palette': 'restaurant brand colors on cream paper or matte black laminate.',
        'seo_context': 'menu printing, restaurant menus, PVC menus, custom menus, cafe menus.',
    },
    'red-packets': {
        'audience': 'US-based Chinese-diaspora businesses, Asian-American wedding planners, and corporate event hosts ordering red packets for Lunar New Year, weddings, and brand giveaways; they need auspicious red-and-gold premium prints.',
        'scene': "A Chinese New Year family gathering or wedding banquet table - red packets fanned, stacked, with gold ingots and tea set, warm golden lighting, traditional red and gold decor.",
        'color_palette': 'auspicious red, metallic gold, rose-gold accents, ivory contrast.',
        'seo_context': 'red packet printing, Chinese New Year red packets, hongbao, foil red packets, wedding red packets.',
    },
    'calendars': {
        'audience': 'US corporates, photographers, schools, and small businesses ordering wall and desk calendars for year-end gifts and promotions; they need full-color, sturdy, spiral-bound calendars.',
        'scene': "An American home office wall or corporate reception desk - calendar mounted or propped, natural daylight, modern clean interior.",
        'color_palette': 'seasonal monthly accent colors on white or charcoal paper.',
        'seo_context': 'calendar printing, wall calendar, desk calendar, custom calendar, 2027 calendar.',
    },
    'banners': {
        'audience': 'US trade-show exhibitors, retail stores, event organizers, real-estate agents and sports teams ordering large-format vinyl banners; they need weatherproof, vivid, durable banners.',
        'scene': "An American outdoor trade-show booth or storefront - banner hung on frame, partially rolled, or stretched, outdoor daylight, urban or event background.",
        'color_palette': 'high-contrast brand colors on white or solid backgrounds.',
        'seo_context': 'banner printing, vinyl banners, outdoor banners, roll-up banners, trade show banners.',
    },
    'envelopes': {
        'audience': 'US small businesses, law firms, real-estate offices, wedding planners and direct-mail marketers ordering custom business envelopes with logo and return address; they need professional, on-brand stationery.',
        'scene': "An American home office desk or business reception - envelopes stacked, fanned, with pen and stamp, soft natural daylight, clean wood and white interior.",
        'color_palette': 'white, ivory, and kraft with subtle brand accent printing.',
        'seo_context': 'envelope printing, custom envelopes, business envelopes, logo envelopes, kraft envelopes.',
    },
    'japan-doujin': {
        'audience': 'Japanese doujin circles, indie comic creators, Comiket exhibitors and anime fan-artists ordering short-run doujinshi and fan-books; they need low MOQ, fast turnaround, and color-accurate cover printing.',
        'scene': "A Japanese doujin event booth or Akihabara studio - doujinshi fanned, stacked, with original-art cover visible, soft studio light, clean modern table setting.",
        'color_palette': 'anime-style vibrant covers on cream or white interior pages.',
        'seo_context': 'doujinshi printing, Comiket printing, fan book printing, short-run book printing, japan doujin print.',
    },
    'greeting-cards': {
        'audience': 'US individuals, small businesses, churches and corporate gift-givers ordering greeting cards for Christmas, New Year, weddings, holidays and brand events; they need premium cardstock with foil and spot-UV options.',
        'scene': "An American holiday gift table or corporate event - greeting cards fanned, stacked with ribbon and gift box, warm holiday lighting, evergreen and red decor.",
        'color_palette': 'festive red/green/gold for Christmas, blush/gold for weddings, brand colors for corporate.',
        'seo_context': 'greeting card printing, custom greeting cards, Christmas cards, holiday cards, foil greeting cards.',
    },
    'wedding-invitations': {
        'audience': 'US engaged couples and wedding planners ordering foil wedding invitations, save-the-dates, thank-you cards and suite stationery; they want elegant, romantic, premium paper goods.',
        'scene': "A bright American garden wedding or elegant reception table - stationery with florals, golden-hour light, white chapel or greenery in soft focus.",
        'color_palette': 'blush pink, ivory cream, champagne gold, soft sage green.',
        'seo_context': 'wedding invitation printing, foil wedding invitations, save the date cards, wedding stationery, wedding suite printing.',
    },
    'place-cards': {
        'audience': 'US engaged couples, wedding planners, fine-dining restaurants, hotel banquet managers and corporate event hosts ordering place cards and table cards; they need premium paper, foil and standing/folded options.',
        'scene': "An American wedding reception table or fine-dining banquet - place cards arranged on plate, escort table, or folded tent-style, soft candlelight, florals and linen in soft focus.",
        'color_palette': 'ivory, blush, champagne gold, sage green, with foil accent.',
        'seo_context': 'place card printing, table cards, escort cards, wedding place cards, custom place cards.',
    },
}

# View templates.  Where-used, view composition, view-specific guards.
VIEW_TEMPLATES = {
    'HERO': {
        'where_used': 'main HERO image on the US product page (zprintpro.com) - the first visual a buyer sees in search results and product grids; it must stop the scroll and earn the click.',
        'composition': 'HERO composition: product centered at 80-85% of frame with clean margin, instantly recognizable, strong first impression, slight angled perspective for depth.',
    },
    'DETAIL': {
        'where_used': 'DETAIL close-up on the US product page - zooms craft and material so buyers trust the quality before purchase.',
        'composition': 'DETAIL composition: extreme close-up filling 85-95% of frame - macro focus on material, texture, edge, foil/lamination or printed detail; shallow depth of field, craftsmanship emphasized.',
    },
    'VARIETY-A': {
        'where_used': 'VARIETY collection image on the US product page - shows options/customization to lift add-to-cart and average order value.',
        'composition': 'VARIETY-A composition: same product design in 3-4 colorway variations arranged neatly, each fully visible, consistent lighting and scale across all variants.',
    },
    'VARIETY-C': {
        'where_used': 'VARIETY collection image on the US product page - shows options/customization to lift add-to-cart and average order value.',
        'composition': 'VARIETY-C composition: 3-4 different designs/styles of this product family grouped in a cohesive lifestyle scene, each item fully visible and clearly the same quality line.',
    },
    'MULTI-ANGLE': {
        'where_used': 'MULTI-ANGLE image on the US product page - shows real dimensions and usability to reduce hesitation and returns.',
        'composition': 'MULTI-ANGLE composition: 3 views of the same product (front, angled, detail-in-context) in one clean frame - shows real dimensions and usability.',
    },
    'SPREAD': {
        'where_used': 'SPREAD image on the US product page - shows unfolded layout for wedding-suite or multi-piece stationery products.',
        'composition': 'SPREAD composition: full spread opened flat 90% of frame, all pieces visible side-by-side, sequential flow, balanced lighting across the full spread.',
    },
}

# Per-SKU view overrides: which 4 views to use.
# Default = HERO + DETAIL + VARIETY-A + MULTI-ANGLE
# Wedding-related (BC + WI) use VARIETY-C instead of VARIETY-A
WEDDING_SLUGS = {
    'premium-greeting-cards', 'holiday-greeting-cards', 'foil-greeting-cards',
    'christmas-cards', 'thank-you-cards', 'wedding-thank-you-cards',
    'foil-wedding-invitations', 'embossed-wedding-invitations', 'modern-wedding-invitations',
    'romantic-wedding-invitations', 'luxury-wedding-invitations', 'simple-wedding-invitations',
    'wedding-place-cards', 'event-place-cards', 'table-cards', 'escort-cards',
    'folded-place-cards', 'standing-place-cards',
}

# Final no-go list
NO_BAD = "No watermark, no AI-generator names, no real luxury brand logos (no Tiffany/Gucci/LV/Chanel), no celebrity faces, no gibberish or placeholder text, no misspelled words, no price lists, no body copy, no barcodes, no torn edges, no plastic toy look, no floating objects, no oversaturation, no harsh flash, no JPEG artifacts."

CRAFT_TRUST = "Photorealistic commercial photography, sharp focus, natural soft lighting, subtle depth of field, true-to-life paper/ink/material texture, premium studio quality that feels honest and professional - the kind of image that makes a US buyer trust an overseas print supplier. Warm, trustworthy, no gimmicks."

US_STYLE = "US-style visual: clean, honest, lifestyle-driven - American shoppers click images that feel real, warm and instantly understandable; no cluttered or over-stylized compositions."

# Skip list - SKUs already manually generated by user 2026-08-22
SKIP_SKUS = {'WI-001', 'PB-001'}


def get_views_for_sku(sku: dict) -> list:
    """Return list of 4 view keys to generate for this SKU."""
    base = ['HERO', 'DETAIL', 'MULTI-ANGLE']
    if sku['slug'] in WEDDING_SLUGS or 'wedding' in sku['category_slug'] or 'place-cards' == sku['category_slug'] or 'greeting-cards' == sku['category_slug']:
        base.insert(2, 'VARIETY-C')
    else:
        base.insert(2, 'VARIETY-A')
    # For wedding-invitations flagship add SPREAD too -> 5 views (only WI-002..WI-006)
    if sku['category_slug'] == 'wedding-invitations' and sku['id'] != 'WI-001':
        base.append('SPREAD')
    return base


def build_prompt(sku: dict, view: str) -> str:
    cat = sku['category_slug']
    cfg = CATEGORY_CONFIG.get(cat, CATEGORY_CONFIG['stickers'])
    v = VIEW_TEMPLATES[view]
    product_text = sku['description_en']
    if len(product_text) > 600:
        product_text = product_text[:597] + '...'
    return (
        f"PRODUCTION-READY FINAL IMAGE ONLY. V22 e-commerce product photography. "
        f"Output 1200x1200 square (Seedream 5.0 lite Direct API, watermark off, no crop needed), "
        f"<=120KB WebP, 8K UHD micro-detail. "
        f"WHERE USED: {v['where_used']} "
        f"AUDIENCE: {cfg['audience']} "
        f"PRODUCT: {product_text} "
        f"SCENE: {cfg['scene']} "
        f"COLOR PALETTE: {cfg['color_palette']} "
        f"{v['composition']} "
        f"CRAFT & TRUST: {CRAFT_TRUST} "
        f"{US_STYLE} "
        f"SEO/GEO CONTEXT: {cfg['seo_context']} "
        f"{NO_BAD}"
    )


def alt_text(sku: dict) -> str:
    """Build the SEO+GEO ALT line for the SKU header."""
    desc = sku['description_en']
    if 'ISO 9001' in desc:
        # keep ISO clause for trust
        head = desc[:220]
        if '**Best for**' in head:
            head = head.split('**Best for**')[0].strip()
        if '**' in head:
            head = head.split('**')[0].strip()
        cfg = CATEGORY_CONFIG.get(sku['category_slug'], CATEGORY_CONFIG['stickers'])
        return f"{head}, ISO 9001:2015 cert {cfg['seo_context']}."
    head = desc[:220]
    if '**Best for**' in head:
        head = head.split('**Best for**')[0].strip()
    if '**' in head:
        head = head.split('**')[0].strip()
    if not head.endswith('.'):
        head += '.'
    return head


def sku_seq(sku_id: str) -> int:
    """Stable SKU sequence number for header (1-based)."""
    m = re.search(r'-(\d+)$', sku_id)
    return int(m.group(1)) if m else 0


def render_block(sku: dict) -> str:
    views = get_views_for_sku(sku)
    lines = []
    lines.append('=' * 78)
    seq = sku_seq(sku['id'])
    seo_file = sku['seo_filename'] or f"(no seo filename - {sku['slug']}-en.webp)"
    lines.append(f"### SKU-{seq:02d} | {sku['id']} | {sku['slug']} | {seo_file}")
    lines.append(f"SEO+GEO ALT: {alt_text(sku)}")
    lines.append('')
    for view in views:
        p = build_prompt(sku, view)
        lines.append(f"[{view}] ({len(p)} chars)")
        lines.append(p)
        lines.append('')
    lines.append('-' * 78)
    return '\n'.join(lines)


def main():
    with open(SKU_DATA_FILE, 'r', encoding='utf-8') as f:
        skus = json.load(f)

    # Sort by SKU id (preserves prefix grouping)
    sorted_skus = [skus[k] for k in sorted(skus.keys())]

    # Build output
    out_lines = []
    out_lines.append('V22 ALL-SKU EN PROMPTS | Seedream 5.0 lite Direct API (watermark:false)')
    out_lines.append('=' * 78)
    out_lines.append('Generated 2026-08-23 from products.ts (99 SKUs total).')
    out_lines.append('Skipped (already manually generated 2026-08-22): WI-001, PB-001')
    out_lines.append('Output: 97 SKUs x 4-5 views = ~390 prompts')
    out_lines.append('Each prompt = 1 API call, 1 image. No regeneration loops.')
    out_lines.append('Size clause: 1200x1200 square (no watermark => no 1200x1146 BOTTOM-STRIP crop needed).')
    out_lines.append('Manual-download mapping: download each result, rename to <SKU>-<VIEW>.webp.')
    out_lines.append('=' * 78)
    out_lines.append('')

    included = 0
    skipped = []
    for sku in sorted_skus:
        if sku['id'] in SKIP_SKUS:
            skipped.append(sku['id'])
            continue
        out_lines.append(render_block(sku))
        out_lines.append('')
        included += 1

    out_lines.append('=' * 78)
    out_lines.append(f'Total: {included} SKUs generated, {len(skipped)} skipped ({", ".join(skipped) or "none"})')
    out_lines.append('=' * 78)

    content = '\n'.join(out_lines)
    OUTPUT_FILE.write_text(content, encoding='utf-8')

    # Summary
    prompt_count = sum(len(get_views_for_sku(s)) for s in sorted_skus if s['id'] not in SKIP_SKUS)
    total_chars = len(content)
    print(f'Output: {OUTPUT_FILE}')
    print(f'Total bytes: {total_chars:,}')
    print(f'SKUs generated: {included}')
    print(f'SKUs skipped: {len(skipped)} ({", ".join(skipped)})')
    print(f'View prompts total: {prompt_count}')
    print(f'Avg per prompt: {total_chars // prompt_count:,} chars')


if __name__ == '__main__':
    main()
