#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""D-7 v2 整改: X-SET → X-HERO (单图) 解决三图并排问题.
K3 8/17 05:20 拍板: '为什么这张图又是三图并排的吗' - 触发根因.
ED-002 CERTIFICATE-SET 被模型理解为 '3 张证书 in one image'.

修法:
- CERTIFICATE-SET → CERTIFICATE-HERO (单张证书主图)
- STICKER-SET → STICKER-HERO (单张贴纸主图, 已有 HERO 时合并到 HERO)
- BAG-FAN → BAG (单张纸袋)
- FAN-OUT → ENVELOPE (单张信封)
- BOX-OPEN → BOX (单张盒子, 不是开盖)
- CALENDAR-OPEN → CALENDAR (单本日历, 不是翻页)
- PAGE-FLIP / WALL-HANG / STAND-UP 改为单图 (PER-SKU 形态)
"""
import json
import os

path = r'zprintpro\.cluster\m3-exec-20260811\enhance_rules.json'
with open(path, 'r', encoding='utf-8') as f:
    rules = json.load(f)

skus = rules['SKUS']

# D-7 v2 视图名重命名 (X-SET/FAN/OPEN → X 单图)
view_rename = {
    'CERTIFICATE-SET': 'CERTIFICATE-HERO',
    'STICKER-SET': 'STICKER-HERO',
    'BAG-FAN': 'BAG-HERO',
    'FAN-OUT': 'ENVELOPE-HERO',
    'BOX-OPEN': 'BOX-HERO',
    'CALENDAR-OPEN': 'CALENDAR-HERO',
    'PAGE-FLIP': 'CALENDAR-PAGE',
    'WALL-HANG': 'CALENDAR-WALL',
    'STAND-UP': 'BANNER-HERO',
    'CARD-STAND': 'CARDS-HERO',  # 也改 (CARD-STAND 仍可能触发多张)
}

# Single-product prompt template (per K3 8/17 05:20 拍板: 单图, 严格 ≥9.0)
single_hero_template = (
    "V20.6 STRICT-SINGLE-IMAGE (K3 8/17 05:20 directive, 解决三图并排问题): "
    "this is a SINGLE PRODUCT HERO image showing exactly ONE {product} - "
    "NOT 3 copies, NOT a set of multiple items, NOT 2 or 3 certificates "
    "side by side. ONE product is the ONLY subject, occupying 60-70% of the frame "
    "with 30-40% clean negative space on all four sides. P0-4 SCENE-SELLING-POINT: "
    "the {product} core selling point must be visually demonstrated. "
    "DESIGN MASTER: from approved DETAIL close-up, the full design (no missing "
    "artwork, no plain surface, no blank product face). V20.6 STRICT >=9.0 "
    "QUALITY GATE (K3 8/17 05:20): this image MUST score >=9.0 on visual quality - "
    "absolutely NO degradation to 8.0-8.9 acceptable. V20.6 ANTI-WATERMARK "
    "NEGATIVES (K3 8/17 04:55 + 05:20 强化, 3 重复强调): no AutoClaw AI watermark, "
    "no autoClaw text, no AutoGLM text, no AI-generated watermark, no text overlay, "
    "no right-bottom-corner watermark, no brand name in any corner, no 'AI 生成' "
    "Chinese text, no 'generated by AI' English text, no 'AI 创作' label. V20.6 "
    "FULL-NO-CROP (K3 8/17 04:55 reaffirmed): 1200x1200 FULL image, no cropping."
)

# Per-SKU 重命名 + 替换 prompt
rename_count = 0
replace_count = 0
for sku, views in skus.items():
    if not isinstance(views, dict):
        continue
    for old_view in list(views.keys()):
        if old_view in view_rename:
            new_view = view_rename[old_view]
            if new_view not in views:
                # Rename: copy to new name + remove old
                views[new_view] = views[old_view]
                # Prepend single-product directive
                product = sku.split('-')[0].lower() if '-' in sku else sku.lower()
                if 'CERTIFICATE' in new_view:
                    product = 'certificate'
                elif 'STICKER' in new_view:
                    product = 'sticker'
                elif 'CARD' in new_view:
                    product = 'card'
                elif 'BAG' in new_view:
                    product = 'paper bag'
                elif 'ENVELOPE' in new_view:
                    product = 'envelope'
                elif 'BOX' in new_view:
                    product = 'box'
                elif 'CALENDAR' in new_view:
                    product = 'calendar'
                elif 'BANNER' in new_view:
                    product = 'banner'
                else:
                    product = sku.lower()
                single_directive = single_hero_template.format(product=product)
                views[new_view] = single_directive + ' ' + views[old_view]
                del views[old_view]
                rename_count += 1
                replace_count += 1
            else:
                # New view already exists, just remove old
                del views[old_view]
                rename_count += 1

rules['SKUS'] = skus
rules['version'] = rules.get('version', '') + ' + D-7-v2-single (2026-08-17 05:20)'

with open(path, 'w', encoding='utf-8') as f:
    json.dump(rules, f, ensure_ascii=False, indent=2)

print('Renamed views:', rename_count)
print('Replaced with single-hero directive:', replace_count)
print('New file size:', os.path.getsize(path), 'bytes')
print('Version:', rules['version'])
print()
# Sample - show ED-002 HERO after rename
if 'ED-002' in skus:
    print('--- ED-002 views after D-7 v2 ---')
    for v, p in skus['ED-002'].items():
        head = p[:200].replace('\n', ' ')
        print('  ' + v + ' (' + str(len(p)) + ' chars): ' + head + '...')
