#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""D-7 v3 整改: 完全废弃 X-SET 概念, 统一 5 标准视图 (K3 8/17 05:20 拍板).
ED-002 三图并排根本原因: D-7 旧整改用 X-SET 概念 (CERTIFICATE-SET), 模型理解为 '3 张 in 1 image'.
修法: 删 VIEW_MAP 中所有 X-SET 映射, 统一用 5 标准视图 (HERO/DETAIL/VARIETY-A/C/MULTI-ANGLE/SPREAD).

K3 8/17 05:20 拍板: 不能降级, 一定要 >9.0 分.
"""
import json
import os

path = r'zprintpro\.cluster\m3-exec-20260811\enhance_rules.json'
with open(path, 'r', encoding='utf-8') as f:
    rules = json.load(f)

# 注入 V20.6 STRICT-SINGLE-IMAGE 到 COMMON 段
v206_strict_clause = (
    " V20.6 STRICT-SINGLE-IMAGE (K3 8/17 05:20 拍板, 解决三图并排问题): "
    "EVERY view generates a SINGLE PRODUCT IMAGE - exactly ONE product is the "
    "subject, NOT 3 copies, NOT a set of multiple items, NOT 2 or 3 certificates "
    "side by side. The product occupies 60-70% of the frame with 30-40% clean "
    "negative space. V20.6 STRICT >=9.0 QUALITY GATE (K3 8/17 05:20 推翻 B 级降级): "
    "this image MUST score >=9.0 - absolutely NO degradation to 8.0-8.9 acceptable. "
    "V20.6 ANTI-WATERMARK NEGATIVES (K3 8/17 04:55 + 05:20 3 重复): "
    "no AutoClaw AI watermark, no autoClaw text, no AutoGLM text, no AI-generated "
    "watermark, no text overlay, no right-bottom-corner watermark, no brand name "
    "in any corner, no 'AI 生成' Chinese text, no 'generated by AI' English text, "
    "no 'AI 创作' label, no AI service brand mark. V20.6 D-7 v3 ABANDON X-SET: "
    "all 'X-SET' / 'X-FAN' / 'X-OPEN' / 'CARD-STAND' multi-item views are ABANDONED - "
    "use 5 standard views (HERO / DETAIL / VARIETY-A or C / MULTI-ANGLE / SPREAD) "
    "with single-product strict mode. V20.6 FULL-NO-CROP: 1200x1200 FULL image, no cropping."
)

rules['COMMON'] = rules['COMMON'] + v206_strict_clause
rules['version'] = rules.get('version', '') + ' + V20.6-strict-9.0-single (2026-08-17 05:20)'

# Write
with open(path, 'w', encoding='utf-8') as f:
    json.dump(rules, f, ensure_ascii=False, indent=2)

print('New file size:', os.path.getsize(path), 'bytes')
print('COMMON new length:', len(rules['COMMON']), 'chars')
print('Version:', rules['version'])
