@echo off
rem K3 v9.4 lane wrapper -- generated by scripts/register-cron-tasks.ps1, do not hand-edit
rem 2026-09-17: repo root = F:\\zprintpro-nextjs (K3 directory iron rule; main-tmp worktree removed)
rem 2026-09-19: preflight (lock + run-context) -> dsh reads results bus FIRST -> host git -> release lock
set PYTHONIOENCODING=utf-8
set PYTHONUTF8=1
cd /d "F:\zprintpro-nextjs"
echo ===== run start %DATE% %TIME% ===== >> "F:\zprintpro-nextjs\.hermes\logs\cron-ZP-blog-deepfix.log"
"C:\Users\Administrator\AppData\Local\hermes\hermes-agent\venv\Scripts\python.exe" "F:\zprintpro-nextjs\scripts\lane-preflight.py" --lane "ZP-blog-deepfix" --repo "F:\zprintpro-nextjs" --acquire >> "F:\zprintpro-nextjs\.hermes\logs\cron-ZP-blog-deepfix.log" 2>&1
set PF=%ERRORLEVEL%
if "%PF%"=="0" goto preflight_ok
echo ===== preflight blocked, dsh NOT called, no lock held ===== >> "F:\zprintpro-nextjs\.hermes\logs\cron-ZP-blog-deepfix.log"
exit /b 1
:preflight_ok
call "C:\Users\Administrator\AppData\Roaming\DSH Desktop\host-commands\desktop\bin\dsh.cmd" --profile headless "STEP 0 (STRICT, results-bus contract = priority -1): FIRST read .hermes/logs/run-context-ZP-blog-deepfix.json and .hermes/logs/lane-status.json, then read .hermes/cron-prompts/lane-results-bus-contract.md (it contains the full Chinese contract text). Use those results as the DATA BASIS for this run: if run-context.retry_queue is non-empty, do those items first and write RETRY_OF in the report; never redo what a previous run already delivered (verdict=OK); never rewrite a file that a sibling lane touched today (cross-lane collision guard). STEP 1: Read .hermes/cron-prompts/zprintpro-blog-deepfix.md and .hermes/cron-prompts/sop-10-gate.md fully, then execute the complete flow for this run (no simplification, no deferral). Work in this repo root (main worktree = deployment source). Write the report to .hermes/logs/<YYYY-MM-DD>-ZP-blog-deepfix.md with the machine-readable first block (VERDICT / CONSUMED / DELIVERED / NEXT) and reply with the report path. Environment note (v9.4 rearm 2026-09-14): the pwsh tool is blocked in this lane sandbox; do NOT retry it. Use file tools (read/glob/grep/write/edit) and web tools only. Git commit/push is handled by the host-side wrapper AFTER this lane exits - you do NOT need to (and cannot) run git yourself. Just produce the content + report on disk; the wrapper commits and pushes automatically." >> "F:\zprintpro-nextjs\.hermes\logs\cron-ZP-blog-deepfix.log" 2>&1
set RC=%ERRORLEVEL%
echo ===== dsh exit=%RC% -- host-side git commit/push -- ===== >> "F:\zprintpro-nextjs\.hermes\logs\cron-ZP-blog-deepfix.log"
"C:\Users\Administrator\AppData\Local\hermes\hermes-agent\venv\Scripts\python.exe" "F:\zprintpro-nextjs\scripts\lane-git-commit.py" --lane "ZP-blog-deepfix" --repo "F:\zprintpro-nextjs" >> "F:\zprintpro-nextjs\.hermes\logs\cron-ZP-blog-deepfix.log" 2>&1
"C:\Users\Administrator\AppData\Local\hermes\hermes-agent\venv\Scripts\python.exe" "F:\zprintpro-nextjs\scripts\lane-preflight.py" --lane "ZP-blog-deepfix" --repo "F:\zprintpro-nextjs" --release >> "F:\zprintpro-nextjs\.hermes\logs\cron-ZP-blog-deepfix.log" 2>&1
echo ===== run end   %DATE% %TIME% exit=%RC% ===== >> "F:\zprintpro-nextjs\.hermes\logs\cron-ZP-blog-deepfix.log"
exit /b %RC%
