@echo off
rem K3 v9.4 lane wrapper -- generated by scripts/register-cron-tasks.ps1, do not hand-edit
rem 2026-09-17: repo root = F:\\zprintpro-nextjs (K3 directory iron rule; main-tmp worktree removed)
rem host-side git commit/push runs after dsh, in the same repo root
set PYTHONIOENCODING=utf-8
set PYTHONUTF8=1
cd /d "F:\zprintpro-nextjs"
echo ===== run start %DATE% %TIME% ===== >> "F:\zprintpro-nextjs\.hermes\logs\cron-ZP-monthly-matrix.log"
call "C:\Users\Administrator\AppData\Roaming\DSH Desktop\host-commands\desktop\bin\dsh.cmd" --profile headless "Read .hermes/cron-prompts/zprintpro-monthly-matrix-audit.md and .hermes/cron-prompts/sop-10-gate.md fully, then execute the complete flow for this run (no simplification, no deferral). Work in this repo root (main worktree = deployment source). Write the report under .hermes/logs/ and reply with the report path. Environment note (v9.4 rearm 2026-09-14): the pwsh tool is blocked in this lane sandbox; do NOT retry it. Use file tools (read/glob/grep/write/edit) and web tools only. Git commit/push is handled by the host-side wrapper AFTER this lane exits - you do NOT need to (and cannot) run git yourself. Just produce the content + report on disk; the wrapper commits and pushes automatically." >> "F:\zprintpro-nextjs\.hermes\logs\cron-ZP-monthly-matrix.log" 2>&1
set RC=%ERRORLEVEL%
echo ===== dsh exit=%RC% -- host-side git commit/push -- ===== >> "F:\zprintpro-nextjs\.hermes\logs\cron-ZP-monthly-matrix.log"
"C:\Users\Administrator\AppData\Local\hermes\hermes-agent\venv\Scripts\python.exe" "F:\zprintpro-nextjs\scripts\lane-git-commit.py" --lane "ZP-monthly-matrix" --repo "F:\zprintpro-nextjs" >> "F:\zprintpro-nextjs\.hermes\logs\cron-ZP-monthly-matrix.log" 2>&1
echo ===== run end   %DATE% %TIME% exit=%RC% ===== >> "F:\zprintpro-nextjs\.hermes\logs\cron-ZP-monthly-matrix.log"
exit /b %RC%
