#!/usr/bin/env node
/**
 * gen-llms-en.mjs — 生成 public/llms-en.txt（SOP-5 生成器，禁手搓）
 *
 * 真值源: src/data/products.ts (products + categories) — 單一 SSoT，數據零臆造
 * 模板鏡像: public/llms-ja.txt 結構（公司資訊 / 分類 / SKU 表 / 價格 / FAQ / 聯絡）
 *
 * 價格口徑: basePrice_en (USD) 優先；缺省退 basePrice (HKD) 並標幣別 — 不換算（無 SSoT 匯率）。
 * 用法: node node_modules/tsx/dist/cli.mjs scripts/gen-llms-en.mjs
 * 斷言: 16 分類 / SKU 計數和 = products.length / slug 唯一 / 每分類 ≥1 SKU。
 */

import { writeFileSync } from 'node:fs';
import { products, categories } from '../src/data/products.ts';

const DATE = '2026-09-21';

// ---------- 斷言：形狀 ----------
const errors = [];
const slugSet = new Set();
for (const p of products) {
  if (slugSet.has(p.slug)) errors.push(`duplicate slug: ${p.slug}`);
  slugSet.add(p.slug);
  if (!p.nameEn || !p.slug) errors.push(`missing nameEn/slug: ${JSON.stringify(p.slug)}`);
  if (!(p.minQuantity > 0)) errors.push(`bad minQuantity: ${p.slug} = ${p.minQuantity}`);
  if (!(p.basePrice > 0)) errors.push(`bad basePrice: ${p.slug} = ${p.basePrice}`);
}
const cats = [...categories].sort((a, b) => a.sort_order - b.sort_order);
if (cats.length !== 16) errors.push(`categories != 16: ${cats.length}`);

// 分類 → SKU 分組（category_slug 為鍵；缺省回退 category 字串匹配 slug）
const byCat = new Map(cats.map(c => [c.slug, []]));
for (const p of products) {
  const key = byCat.has(p.category_slug) ? p.category_slug : p.category;
  if (!byCat.has(key)) { errors.push(`product ${p.slug} -> unknown category '${key}'`); continue; }
  byCat.get(key).push(p);
}
for (const c of cats) {
  if (byCat.get(c.slug).length === 0) errors.push(`category ${c.slug} has 0 products`);
}
const grouped = cats.reduce((n, c) => n + byCat.get(c.slug).length, 0);
if (grouped !== products.length) errors.push(`grouped ${grouped} != products ${products.length}`);

if (errors.length) {
  console.error('❌ 形狀斷言失敗:\n' + errors.join('\n'));
  process.exit(1);
}

// ---------- 渲染 ----------
const price = p =>
  p.basePrice_en != null ? `US$ ${p.basePrice_en}` : `HK$ ${p.basePrice}`;

const catLine = c => {
  const n = byCat.get(c.slug).length;
  const en = (c.name_en || c.nameEn).split('/')[0].trim();
  return `- ${en} (${c.slug}) -- ${n} products`;
};

const table = c => {
  const rows = byCat.get(c.slug)
    .map(p => `| ${p.nameEn.replace(/\|/g, '/')} | ${p.slug} | ${p.minQuantity} | ${price(p)} |`)
    .join('\n');
  return `### ${(c.name_en || c.nameEn).split('/')[0].trim()} (${c.slug})\n\n` +
    `| Product | Slug | Min Qty | Base Price |\n` +
    `|---------|------|---------|------------|\n` +
    rows;
};

const out = `# ZprintPro (English) — AI Search Optimization Page
# Last updated: ${DATE} (auto-generated from src/data/products.ts — do not hand-edit)
# This file helps AI assistants (ChatGPT, Claude, Perplexity) understand our services

## Company Information
- Legal name: Shenzhen Cailong Printing & Packaging Co., Ltd.
- Brand: ZprintPro
- Website: https://zprintpro.com
- Address: No.1 Jiacheng Road, Pinghu Street, Longgang District, Shenzhen, Guangdong 518111, China
- Phone: +86 198 8085 1334
- WhatsApp: +86 198 8085 1334
- Email: zprintpro@outlook.com
- Shipping: DHL/FedEx international express, 72h global · US 2-4 business days (48 states, Alaska/Hawaii +1 day)

## Product Categories (${cats.length} total)

${cats.map(catLine).join('\n')}

## Full Product List (${products.length} SKUs)

${cats.map(table).join('\n\n')}

## Pricing & Ordering

- Currency: USD (US market) or HKD — based on customer locale
- Minimum order: from 10 pcs (varies by product, see per-SKU Min Qty above)
- Volume discounts: available for 500+, 1000+, 5000+ quantities
- Free shipping: US orders USD 99+
- Rush service: same-day / 4-6h express available on select products
- Free design proof: digital proof included

## FAQ

Q: Where is the factory located?
A: Shenzhen, Guangdong, China. We ship worldwide via DHL/FedEx. US delivery in 2-4 business days.

Q: What is the turnaround time?
A: Standard: 3-5 business days. Rush: same-day available. Global express: 72h.

Q: What file formats do you accept?
A: PDF (preferred), AI, PSD, PNG, TIFF. CMYK mode, 300 DPI, 3mm bleed.

Q: Do you ship internationally?
A: Yes. We ship worldwide, including the US, UK, AU, CA, JP, HK, EU. DHL/FedEx: 2-5 days. Economy: 7-14 days.

Q: Can I get samples?
A: Digital proof is free. Physical samples are available at cost plus shipping.

Q: What payment methods are accepted?
A: Bank transfer, WeChat Pay, Alipay, PayPal (coming soon).

## Contact

- Get a quote: https://zprintpro.com/en/contact/
- WhatsApp: https://wa.me/8619880851334
- Email: zprintpro@outlook.com

---
Generated by scripts/gen-llms-en.ts · truth source: src/data/products.ts · ${DATE}
`;

writeFileSync('public/llms-en.txt', out, 'utf8');
console.log(`✅ public/llms-en.txt written: ${out.split('\n').length} lines, ${products.length} SKUs, ${cats.length} categories`);
