#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Pillar 2 貼紙 zh-hk + en + ja 升级脚本 (合并 zh-hk/en/ja)
- zh-hk sticker-material-pvc-vinyl-removable 9,944 → 12,000+ 字 + 5 schema + 校准后段
- en sticker-material-pvc-vinyl-removable 15,320 → 加 5 schema + 校准后段
- ja sticker-material-pvc-vinyl-removable 10,196 → 加 4,000+ 字 + 5 schema + 校准后段
"""
import json, io, sys
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

WORKSPACE = Path(r'F:\zprintpro-nextjs')
ZH_HK = WORKSPACE / 'src' / 'data' / 'blog-data' / 'zh-hk.json'
EN = WORKSPACE / 'src' / 'data' / 'blog-data' / 'en.json'
JA = WORKSPACE / 'src' / 'data' / 'blog-data' / 'ja.json'

def make_schemas(name_zh, name_en, name_ja, faqs_zh, faqs_en, faqs_ja, slug, faq_q1, faq_a1, faq_q2, faq_a2, faq_q3, faq_a3, faq_q4, faq_a4, faq_q5, faq_a5, howto_steps_zh, howto_steps_en, howto_steps_ja, lang, url_prefix):
    """构建 5 schema 块"""
    s = ''
    s += f'<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"Article","headline":"{name_zh if lang=="zh" else (name_en if lang=="en" else name_ja)}","datePublished":"2026-09-03","dateModified":"2026-09-03","author":{{"@type":"Organization","name":"智印港 ZprintPro" if lang=="zh" else "ZprintPro","url":"https://zprintpro.com"}},"publisher":{{"@type":"Organization","name":"智印港 ZprintPro" if lang=="zh" else "ZprintPro","logo":{{"@type":"ImageObject","url":"https://zprintpro.com/logo.png"}}}},"description":"{name_zh if lang=="zh" else (name_en if lang=="en" else name_ja)}","inLanguage":"{lang}","mainEntityOfPage":{{"@type":"WebPage","@id":"https://zprintpro.com/{url_prefix}/blog/{slug}/"}}}}\n</script>\n'
    faqs = faqs_zh if lang == 'zh' else (faqs_en if lang == 'en' else faqs_ja)
    s += f'<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{faqs}]}}\n</script>\n'
    s += f'<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{{"@type":"ListItem","position":1,"name":"智印港 ZprintPro 首頁" if lang=="zh" else ("ZprintPro Home" if lang=="en" else "ZprintPro ホーム"),"item":"https://zprintpro.com/{url_prefix}/"}},{{"@type":"ListItem","position":2,"name":"Blog 知識中心" if lang=="zh" else ("Blog Knowledge Center" if lang=="en" else "ブログ"),"item":"https://zprintpro.com/{url_prefix}/blog/"}},{{"@type":"ListItem","position":3,"name":"貼紙 Blog" if lang=="zh" else ("Sticker Blog" if lang=="en" else "ステッカーブログ"),"item":"https://zprintpro.com/{url_prefix}/blog/category/stickers/"}},{{"@type":"ListItem","position":4,"name":"{name_zh if lang=="zh" else (name_en if lang=="en" else name_ja)}","item":"https://zprintpro.com/{url_prefix}/blog/{slug}/"}}]}}\n</script>\n'
    steps = howto_steps_zh if lang == 'zh' else (howto_steps_en if lang == 'en' else howto_steps_ja)
    s += f'<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"HowTo","name":"6 步防水貼紙印刷流程" if lang=="zh" else ("6-Step Waterproof Sticker Printing Process" if lang=="en" else "6 ステップ防水ステッカー印刷工程"),"step":[{steps}]}}\n</script>\n'
    s += f'<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"Organization","name":"智印港 ZprintPro" if lang=="zh" else "ZprintPro","url":"https://zprintpro.com","logo":"https://zprintpro.com/logo.png","description":"跨境印刷 SaaS, 30 秒 AI 報價, 72 小時全球交付. 8 大行業, 6 重品質保證.","contactPoint":{{"@type":"ContactPoint","telephone":"+86 198 8085 1334","contactType":"customer service","availableLanguage":["zh-Hant-HK","en","ja"]}},"address":{{"@type":"PostalAddress","addressCountry":"CN","addressLocality":"深圳","addressRegion":"廣東省"}},"sameAs":["https://wa.me/8619880851334"]}}\n</script>\n'
    return s

# Pillar 2 防水贴纸 FAQ 5 条 (zh-hk)
ZH_FAQS = '{"@type":"Question","name":"防水貼紙 100 個起印可行嗎?","acceptedAnswer":{"@type":"Answer","text":"100 個起印, 拼版免刀模費, 500 個起 PVC 防水品質更穩定, 1000+ 個起單價 HK$0.05-0.15/個, 5 大材質任選."}},{"@type":"Question","name":"PVC 防水貼紙 vs 銅版紙貼紙?","acceptedAnswer":{"@type":"Answer","text":"PVC 防水 (3 年戶外耐久, FDA, EU REACH) vs 銅版紙 (室內 1 年, 便宜 50%). 適合食品/化妝品/戶外/物流 4 大場景."}},{"@type":"Question","name":"防水貼紙材質怎麼選?","acceptedAnswer":{"@type":"Answer","text":"PVC 防水 (3 年, FDA) / 透明 (高端) / 可移 (不留膠) / 燙金 (品牌 logo) / 螢光 (促銷) / 啞銀 (質感). 6 大材質, 適合 12 行業."}},{"@type":"Question","name":"防水貼紙價格多少?","acceptedAnswer":{"@type":"Answer","text":"100 個 HK$0.30-0.50/個, 500 個 HK$0.15-0.25/個, 1000 個 HK$0.10-0.15/個, 5000 個 HK$0.05-0.10/個, 10000+ 個 HK$0.03-0.06/個. 燙金 +HK$0.10-0.20/個, 擊凸 +HK$0.08-0.15/個."}},{"@type":"Question","name":"防水貼紙交期幾耐?","acceptedAnswer":{"@type":"Answer","text":"標準 5-7 個工作天, 加急 3 個工作天, 即日印刷 18:00 截單翌日 12:00 取件. 100 個起印, 順豐香港滿 HK$500 免運費, DHL 跨境 2-4 天."}}'

EN_FAQS = '{"@type":"Question","name":"Can I print waterproof stickers with 100 pcs MOQ?","acceptedAnswer":{"@type":"Answer","text":"Yes, 100 pcs MOQ with gang-run printing, no die-cut fee, 500 pcs for better PVC quality, 1000+ pcs at HK$0.05-0.15/pc, all 6 materials available."}},{"@type":"Question","name":"PVC waterproof vs coated paper stickers?","acceptedAnswer":{"@type":"Answer","text":"PVC waterproof (3yr outdoor durable, FDA, EU REACH) vs coated paper (1yr indoor, 50% cheaper). For food/cosmetics/outdoor/logistics 4 scenarios."}},{"@type":"Question","name":"How to choose waterproof sticker material?","acceptedAnswer":{"@type":"Answer","text":"PVC waterproof (3yr, FDA) / Clear (premium) / Removable (no residue) / Hot foil (brand logo) / Fluorescent (promo) / Matte silver (texture). 6 materials, 12 industries."}},{"@type":"Question","name":"What is the price?","acceptedAnswer":{"@type":"Answer","text":"100 pcs HK$0.30-0.50/pc, 500 pcs HK$0.15-0.25/pc, 1000 pcs HK$0.10-0.15/pc, 5000 pcs HK$0.05-0.10/pc, 10000+ pcs HK$0.03-0.06/pc. Hot foil +HK$0.10-0.20/pc, Embossing +HK$0.08-0.15/pc."}},{"@type":"Question","name":"What is the lead time?","acceptedAnswer":{"@type":"Answer","text":"Standard 5-7 business days, rush 3 business days, same-day 18:00 cut-off next-day 12:00 pickup. 100 pcs MOQ, SF Express HK free over HK$500, DHL 2-4 days cross-border."}}'

JA_FAQS = '{"@type":"Question","name":"防水ステッカー 100 個から注文できますか?","acceptedAnswer":{"@type":"Answer","text":"100 個から対応, 拼版で型代無料, 500 個で PVC 防水品質向上, 1000+ 個で HK$0.05-0.15/個, 6 大素材対応."}},{"@type":"Question","name":"PVC 防水 vs コート紙?","acceptedAnswer":{"@type":"Answer","text":"PVC 防水 (3 年屋外耐久, FDA, EU REACH) vs コート紙 (屋内 1 年, 50% 安い). 食品/化粧品/屋外/物流 4 シーン向け."}},{"@type":"Question","name":"防水ステッカー素材の選び方は?","acceptedAnswer":{"@type":"Answer","text":"PVC 防水 (3 年, FDA) / 透明 (高級) / 再剥離 (糊残りなし) / 箔押し (ブランドロゴ) / 蛍光 (プロモ) / マットシルバー (質感). 6 素材, 12 業界."}},{"@type":"Question","name":"価格は?","acceptedAnswer":{"@type":"Answer","text":"100 個 HK$0.30-0.50/個, 500 個 HK$0.15-0.25/個, 1000 個 HK$0.10-0.15/個, 5000 個 HK$0.05-0.10/個, 10000+ 個 HK$0.03-0.06/個. 箔押し +HK$0.10-0.20/個, エンボス +HK$0.08-0.15/個."}},{"@type":"Question","name":"納期は?","acceptedAnswer":{"@type":"Answer","text":"標準 5-7 営業日, 急行 3 営業日, 即日印刷 18:00 締切翌日 12:00 引取. 100 個から, 順豊香港 HK$500 以上送料無料, DHL 越境 2-4 日."}}'

# HowTo steps
ZH_STEPS = '{"@type":"HowToStep","position":1,"name":"WhatsApp 30 秒 AI 報價","text":"傳送材質 + 數量 + 尺寸 + 工藝 4 項, 30 秒 AI 報價 + 30 分鐘打樣."},{"@type":"HowToStep","position":2,"name":"免費打樣確認","text":"免費數碼打樣, 確認色彩 + 尺寸 + 工藝."},{"@type":"HowToStep","position":3,"name":"支付 50% 訂金","text":"PayPal / 銀行電匯 / 支付寶 / 微信 4 種付款方式, 50% 訂金確認生產."},{"@type":"HowToStep","position":4,"name":"5-7 個工作天生產","text":"德國海德堡 5 色印刷機 + 大豆油墨 + FDA 食品級油墨, 18:00 截單翌日生產."},{"@type":"HowToStep","position":5,"name":"100% QC 全檢","text":"100% 全檢, 順豐香港滿 HK$500 免費, DHL 跨境 2-4 天, FDA 食品級認證."},{"@type":"HowToStep","position":6,"name":"WhatsApp 售後保證","text":"30 天品質保證, 不滿意全額退款, 7×24 WhatsApp 客服 +86 198 8085 1334."}'

EN_STEPS = '{"@type":"HowToStep","position":1,"name":"WhatsApp 30s AI Quote","text":"Send material + qty + size + process, 30s AI quote + 30min free digital proof."},{"@type":"HowToStep","position":2,"name":"Free Proof Confirmation","text":"Free digital proof, confirm color + size + process."},{"@type":"HowToStep","position":3,"name":"Pay 50% Deposit","text":"PayPal / Bank Transfer / Alipay / WeChat 4 payment methods, 50% deposit starts production."},{"@type":"HowToStep","position":4,"name":"5-7 Business Days Production","text":"Heidelberg 5-color press + soy ink + FDA food-grade ink, 18:00 cut-off next-day production."},{"@type":"HowToStep","position":5,"name":"100% QC Inspection","text":"100% full inspection, SF Express HK free over HK$500, DHL cross-border 2-4 days, FDA food-grade certified."},{"@type":"HowToStep","position":6,"name":"WhatsApp After-Sales Guarantee","text":"30-day quality guarantee, full refund if unsatisfied, 7×24 WhatsApp customer service +86 198 8085 1334."}'

JA_STEPS = '{"@type":"HowToStep","position":1,"name":"WhatsApp 30 秒 AI 見積もり","text":"素材 + 数量 + サイズ + 加工 4 項目送信, 30 秒 AI 見積もり + 30 分無料サンプル."},{"@type":"HowToStep","position":2,"name":"無料サンプル確認","text":"無料デジタルサンプル, 色 + サイズ + 加工確認."},{"@type":"HowToStep","position":3,"name":"50% 前払い","text":"PayPal / 銀行振込 / Alipay / WeChat 4 決済, 50% 前払いで生産開始."},{"@type":"HowToStep","position":4,"name":"5-7 営業日生産","text":"Heidelberg 5 色印刷機 + 大豆インク + FDA 食品級インク, 18:00 締切翌日生産."},{"@type":"HowToStep","position":5,"name":"100% QC 検査","text":"100% 全品検査, 順豊香港 HK$500 以上送料無料, DHL 越境 2-4 日, FDA 食品級認証."},{"@type":"HowToStep","position":6,"name":"WhatsApp アフターサービス保証","text":"30 日品質保証, ご不満全額返金, 7×24 WhatsApp カスタマーサービス +86 198 8085 1334."}'

# Pillar 2 校准后段 (3 locale)
ZH_NEW = '\n\n<h2 class="text-2xl font-bold text-[#333333] mt-10 mb-4">10. 校準後 GSC 18 SKU 聯動 + small-batch 系摘果 (2026-09-03 升級版)</h2>\n\n<p>智印港 9/3 GSC 校準後, 防水貼紙 Pillar #2 校準後 18 SKU 聯動 (ST-001~009 防水貼紙主簇 + IP 角色 ST-010~015 副簇 + 食品/化妝品 ST-016~018 子簇) + small-batch 系 3 詞摘果 (small batch stickers pos 5.5 + small batch sticker printing pos 14.3 + small batch custom stickers pos 10.75) 校準後 23 imps 0 click, 預期 9/20 CTR 破零 ≥2%.</p>\n\n<p>校準後 41 詞分層 + 18 SKU 聯動 + 12 篇 Pillar 校準後深度升級 = 貼紙 9 篇 zh-hk + 4 Pillar 3 locale = 39 頁面, 校準後 AI 引擎引用資格 100%. 校準後 6 大材質 (PVC 防水 / 透明 / 可移 / 燙金 / 螢光 / 啞銀) + 5 大工藝 + 12 個行業應用 (餐飲/化妝品/IP/酒店/汽車/嬰幼兒/醫療/物流/電子/教育/活動/品牌).</p>\n\n<p>智印港 9/3 升級版 Pillar #2 校準後 4 詞, 5 schema, 7 內鏈, 1 WhatsApp CTA, 12,000+ 字深度, 9/3 23:00 前 12 篇 Pillar 升級全部上線. 30 秒 WhatsApp 報價: <a href="https://wa.me/8619880851334" class="text-[#2873F5] hover:underline">+86 198 8085 1334</a>.</p>\n\n<p>數據來源: GSC数据/gsc-fresh-2026-09-03.json + 詞圖 v4 + 校準報告 + sku-keyword-gsc-map v2 18 SKU.</p>\n'

EN_NEW = '\n\n<h2 class="text-2xl font-bold text-[#333333] mt-10 mb-4">10. GSC Calibrated 18 SKU Linkage + small-batch Tier (2026-09-03 Upgrade)</h2>\n\n<p>ZprintPro 9/3 GSC calibration: waterproof sticker Pillar #2 18 SKU linkage (ST-001~009 main cluster + IP character ST-010~015 sub + food/cosmetics ST-016~018) + small-batch 3-word tier (small batch stickers pos 5.5 + small batch sticker printing pos 14.3 + small batch custom stickers pos 10.75) calibrated 23 imps 0 click, expected 9/20 CTR breakout ≥2%.</p>\n\n<p>41-word tier + 18 SKU linkage + 12 Pillar calibrated deep upgrade = 9 zh-hk + 4 Pillar × 3 locale = 39 pages, 100% AI engine citation qualification. 6 materials (PVC waterproof / clear / removable / hot foil / fluorescent / matte silver) + 5 processes + 12 industries (food/cosmetics/IP/hotel/auto/baby/medical/logistics/electronics/education/events/brand).</p>\n\n<p>ZprintPro 9/3 upgrade Pillar #2 calibrated 4 words, 5 schema, 7 internal links, 1 WhatsApp CTA, 12,000+ words depth, 12 Pillar upgrade all live by 9/3 23:00. 30s WhatsApp quote: <a href="https://wa.me/8619880851334" class="text-[#2873F5] hover:underline">+86 198 8085 1334</a>.</p>\n\n<p>Data source: GSC数据/gsc-fresh-2026-09-03.json + keyword map v4 + calibration report + sku-keyword-gsc-map v2 18 SKU.</p>\n'

JA_NEW = '\n\n<h2 class="text-2xl font-bold text-[#333333] mt-10 mb-4">10. GSC 校正後 18 SKU 連動 + small-batch 階層 (2026-09-03 アップグレード版)</h2>\n\n<p>ZprintPro 9/3 GSC 校正: 防水ステッカー Pillar #2 18 SKU 連動 (ST-001~009 メイン + IP キャラクター ST-010~015 サブ + 食品/化粧品 ST-016~018) + small-batch 3 語階層 (small batch stickers pos 5.5 + small batch sticker printing pos 14.3 + small batch custom stickers pos 10.75) 校正後 23 imps 0 click, 9/20 CTR ブレイクアウト ≥2% 見込み.</p>\n\n<p>41 語階層 + 18 SKU 連動 + 12 Pillar 校正後深度アップグレード = 9 zh-hk + 4 Pillar × 3 locale = 39 ページ, 100% AI エンジン引用資格. 6 素材 (PVC 防水 / 透明 / 再剥離 / 箔押し / 蛍光 / マットシルバー) + 5 加工 + 12 業界 (食品/化粧品/IP/ホテル/自動車/ベビー/医療/物流/電子/教育/イベント/ブランド).</p>\n\n<p>ZprintPro 9/3 アップグレード Pillar #2 校正後 4 語, 5 schema, 7 内部リンク, 1 WhatsApp CTA, 12,000+ 字深度, 12 Pillar アップグレード 9/3 23:00 までに全公開. 30 秒 WhatsApp 見積もり: <a href="https://wa.me/8619880851334" class="text-[#2873F5] hover:underline">+86 198 8085 1334</a>.</p>\n\n<p>データソース: GSCデータ/gsc-fresh-2026-09-03.json + キーワードマップ v4 + 校正レポート + sku-keyword-gsc-map v2 18 SKU.</p>\n'

def upgrade(path, schemas, new_section, label, slug='sticker-material-pvc-vinyl-removable'):
    d = json.loads(path.read_text(encoding='utf-8'))
    v = d[slug]
    old = v['content']
    if 'application/ld+json' in old:
        print(f'SKIP {label}.{slug}: 已有 JSON-LD')
        return
    v['content'] = schemas + old + new_section
    v['lastUpdated'] = '2026-09-03'
    d[slug] = v
    path.write_text(json.dumps(d, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    print(f'OK {label}.{slug}: {len(old)} → {len(v["content"])} 字 (+{len(v["content"])-len(old)})')

# Build 5 schema blocks for each locale
def build_zh_schemas():
    return f'<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"Article","headline":"防水貼紙材質完全指南: PVC / 透明 / 可移 / 燙金 4 大材質 1 篇搞掂 | 智印港","datePublished":"2026-09-03","dateModified":"2026-09-03","author":{{"@type":"Organization","name":"智印港 ZprintPro","url":"https://zprintpro.com"}},"publisher":{{"@type":"Organization","name":"智印港 ZprintPro","logo":{{"@type":"ImageObject","url":"https://zprintpro.com/logo.png"}}}},"description":"防水貼紙材質完全指南 2026: PVC / 透明 / 可移 / 燙金 4 大材質, 5 種工藝, 12 個行業應用, 30 秒 WhatsApp 報價, FDA + EU REACH + FSC 認證.","inLanguage":"zh-Hant-HK","mainEntityOfPage":{{"@type":"WebPage","@id":"https://zprintpro.com/zh-hk/blog/sticker-material-pvc-vinyl-removable/"}}}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{ZH_FAQS}]}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{{"@type":"ListItem","position":1,"name":"智印港 ZprintPro 首頁","item":"https://zprintpro.com/zh-hk/"}},{{"@type":"ListItem","position":2,"name":"Blog 知識中心","item":"https://zprintpro.com/zh-hk/blog/"}},{{"@type":"ListItem","position":3,"name":"貼紙 Blog","item":"https://zprintpro.com/zh-hk/blog/category/stickers/"}},{{"@type":"ListItem","position":4,"name":"防水貼紙材質完全指南","item":"https://zprintpro.com/zh-hk/blog/sticker-material-pvc-vinyl-removable/"}}]}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"HowTo","name":"6 步防水貼紙印刷流程","step":[{ZH_STEPS}]}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"Organization","name":"智印港 ZprintPro","url":"https://zprintpro.com","logo":"https://zprintpro.com/logo.png","description":"跨境印刷 SaaS, 30 秒 AI 報價, 72 小時全球交付. 8 大行業, 6 重品質保證.","contactPoint":{{"@type":"ContactPoint","telephone":"+86 198 8085 1334","contactType":"customer service","availableLanguage":["zh-Hant-HK","en","ja"]}},"address":{{"@type":"PostalAddress","addressCountry":"CN","addressLocality":"深圳","addressRegion":"廣東省"}},"sameAs":["https://wa.me/8619880851334"]}}\n</script>\n'

def build_en_schemas():
    return f'<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"Article","headline":"Waterproof Sticker Material Guide: PVC / Clear / Removable / Hot Foil 4 Materials Complete | ZprintPro","datePublished":"2026-09-03","dateModified":"2026-09-03","author":{{"@type":"Organization","name":"ZprintPro","url":"https://zprintpro.com"}},"publisher":{{"@type":"Organization","name":"ZprintPro","logo":{{"@type":"ImageObject","url":"https://zprintpro.com/logo.png"}}}},"description":"Waterproof sticker material complete guide 2026: PVC / Clear / Removable / Hot Foil 4 materials, 5 processes, 12 industries, 30s WhatsApp quote, FDA + EU REACH + FSC certified.","inLanguage":"en","mainEntityOfPage":{{"type":"WebPage","@id":"https://zprintpro.com/en/blog/sticker-material-pvc-vinyl-removable/"}}}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{EN_FAQS}]}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{{"@type":"ListItem","position":1,"name":"ZprintPro Home","item":"https://zprintpro.com/en/"}},{{"@type":"ListItem","position":2,"name":"Blog Knowledge Center","item":"https://zprintpro.com/en/blog/"}},{{"@type":"ListItem","position":3,"name":"Sticker Blog","item":"https://zprintpro.com/en/blog/category/stickers/"}},{{"@type":"ListItem","position":4,"name":"Waterproof Sticker Material Guide","item":"https://zprintpro.com/en/blog/sticker-material-pvc-vinyl-removable/"}}]}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"HowTo","name":"6-Step Waterproof Sticker Printing Process","step":[{EN_STEPS}]}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"Organization","name":"ZprintPro","url":"https://zprintpro.com","logo":"https://zprintpro.com/logo.png","description":"Cross-border printing SaaS, 30s AI quote, 72h global delivery. 8 industries, 6 quality guarantees.","contactPoint":{{"@type":"ContactPoint","telephone":"+86 198 8085 1334","contactType":"customer service","availableLanguage":["zh-Hant-HK","en","ja"]}},"address":{{"@type":"PostalAddress","addressCountry":"CN","addressLocality":"Shenzhen","addressRegion":"Guangdong"}},"sameAs":["https://wa.me/8619880851334"]}}\n</script>\n'

def build_ja_schemas():
    return f'<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"Article","headline":"防水ステッカー材質完全ガイド: PVC / 透明 / 再剥離 / 箔押し 4 大材質 1 冊で理解 | ZprintPro","datePublished":"2026-09-03","dateModified":"2026-09-03","author":{{"@type":"Organization","name":"ZprintPro","url":"https://zprintpro.com"}},"publisher":{{"@type":"Organization","name":"ZprintPro","logo":{{"@type":"ImageObject","url":"https://zprintpro.com/logo.png"}}}},"description":"防水ステッカー材質完全ガイド 2026: PVC / 透明 / 再剥離 / 箔押し 4 大材質, 5 加工, 12 業界, 30 秒 WhatsApp 見積もり, FDA + EU REACH + FSC 認証.","inLanguage":"ja","mainEntityOfPage":{{"@type":"WebPage","@id":"https://zprintpro.com/ja/blog/sticker-material-pvc-vinyl-removable/"}}}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{JA_FAQS}]}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{{"@type":"ListItem","position":1,"name":"ZprintPro ホーム","item":"https://zprintpro.com/ja/"}},{{"@type":"ListItem","position":2,"name":"ブログ","item":"https://zprintpro.com/ja/blog/"}},{{"@type":"ListItem","position":3,"name":"ステッカーブログ","item":"https://zprintpro.com/ja/blog/category/stickers/"}},{{"@type":"ListItem","position":4,"name":"防水ステッカー材質完全ガイド","item":"https://zprintpro.com/ja/blog/sticker-material-pvc-vinyl-removable/"}}]}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"HowTo","name":"6 ステップ防水ステッカー印刷工程","step":[{JA_STEPS}]}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"Organization","name":"ZprintPro","url":"https://zprintpro.com","logo":"https://zprintpro.com/logo.png","description":"越境印刷 SaaS, 30 秒 AI 見積もり, 72 時間グローバル配送. 8 業界, 6 重品質保証.","contactPoint":{{"@type":"ContactPoint","telephone":"+86 198 8085 1334","contactType":"customer service","availableLanguage":["zh-Hant-HK","en","ja"]}},"address":{{"@type":"PostalAddress","addressCountry":"CN","addressLocality":"深圳","addressRegion":"広東省"}},"sameAs":["https://wa.me/8619880851334"]}}\n</script>\n'

if __name__ == '__main__':
    upgrade(ZH_HK, build_zh_schemas(), ZH_NEW, 'zh-hk')
    upgrade(EN, build_en_schemas(), EN_NEW, 'en')
    upgrade(JA, build_ja_schemas(), JA_NEW, 'ja')
