#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Pillar 3 宣傳單張 (海報/傳單) zh-hk + en + ja 升级脚本
- zh-hk poster-size-guide 13,035 → 加 5 schema JSON-LD + 校准后段
- en poster-size-guide 19,096 → 加 5 schema JSON-LD + 校准后段
- ja poster-size-guide 13,699 → 加 5 schema JSON-LD + 校准后段
"""
import json, io, sys
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

WORKSPACE = Path(r'F:\zprintpro-nextjs')
ZH_HK = WORKSPACE / 'src' / 'data' / 'blog-data' / 'zh-hk.json'
EN = WORKSPACE / 'src' / 'data' / 'blog-data' / 'en.json'
JA = WORKSPACE / 'src' / 'data' / 'blog-data' / 'ja.json'

# FAQs for Pillar 3 宣传单张 (a1a2 海报摘果)
ZH_FAQS = '{"@type":"Question","name":"海報印刷 1 張起印可行嗎?","acceptedAnswer":{"@type":"Answer","text":"A1/A2/A3/A4 海報 1 張起印, 100 張起單價 HK$3-8/張, 防水材質 + 急件翌日取件 + DHL 全球 2-4 天."}},{"@type":"Question","name":"a1 a2 海報印刷材質怎麼選?","acceptedAnswer":{"@type":"Answer","text":"157gsm 銅版紙 (室內 1 年) / 250gsm 啞粉紙 (高端) / 200gsm 防水 PVC (3 年戶外) / 帆布 (展覽). 4 大材質."}},{"@type":"Question","name":"海報印刷價格多少?","acceptedAnswer":{"@type":"Answer","text":"A4 1 張 HK$5-15, A3 1 張 HK$15-30, A2 1 張 HK$30-60, A1 1 張 HK$60-120. 100 張起更平, 防水 +50%, 急件 +30%."}},{"@type":"Question","name":"海報印刷交期幾耐?","acceptedAnswer":{"@type":"Answer","text":"標準 3-5 個工作天, 加急 1-2 個工作天, 即日印刷 18:00 截單翌日 12:00 取件. 1 張起印, 順豐香港滿 HK$500 免運費, DHL 跨境 2-4 天."}},{"@type":"Question","name":"海報印刷 5 大工藝?","acceptedAnswer":{"@type":"Answer","text":"4C+0 印刷 (基本) / 4C+4C 雙面 / 防水過膠 (亮/啞) / 燙金 (高端) / 打孔 + 掛繩 (展覽). 5 大工藝."}}'

EN_FAQS = '{"@type":"Question","name":"Can I print posters with 1 pc MOQ?","acceptedAnswer":{"@type":"Answer","text":"A1/A2/A3/A4 posters 1 pc MOQ, 100 pcs at HK$3-8/pc, waterproof + rush next-day + DHL 2-4 days global."}},{"@type":"Question","name":"How to choose a1 a2 poster material?","acceptedAnswer":{"@type":"Answer","text":"157gsm coated (1yr indoor) / 250gsm matte (premium) / 200gsm waterproof PVC (3yr outdoor) / canvas (exhibition). 4 materials."}},{"@type":"Question","name":"What is the price?","acceptedAnswer":{"@type":"Answer","text":"A4 1 pc HK$5-15, A3 1 pc HK$15-30, A2 1 pc HK$30-60, A1 1 pc HK$60-120. 100 pcs cheaper, waterproof +50%, rush +30%."}},{"@type":"Question","name":"What is the lead time?","acceptedAnswer":{"@type":"Answer","text":"Standard 3-5 business days, rush 1-2 business days, same-day 18:00 cut-off next-day 12:00 pickup. 1 pc MOQ, SF Express HK free over HK$500, DHL 2-4 days cross-border."}},{"@type":"Question","name":"5 poster processes?","acceptedAnswer":{"@type":"Answer","text":"4C+0 (basic) / 4C+4C double-sided / waterproof lamination (glossy/matte) / hot foil (premium) / hole + rope (exhibition). 5 processes."}}'

JA_FAQS = '{"@type":"Question","name":"ポスター印刷 1 枚から注文できますか?","acceptedAnswer":{"@type":"Answer","text":"A1/A2/A3/A4 ポスター 1 枚から対応, 100 枚 HK$3-8/枚, 防水素材 + 急行翌日 + DHL 越境 2-4 日."}},{"@type":"Question","name":"a1 a2 ポスター素材の選び方は?","acceptedAnswer":{"@type":"Answer","text":"157gsm コート紙 (屋内 1 年) / 250gsm マット (高級) / 200gsm 防水 PVC (3 年屋外) / キャンバス (展示). 4 素材."}},{"@type":"Question","name":"価格は?","acceptedAnswer":{"@type":"Answer","text":"A4 1 枚 HK$5-15, A3 1 枚 HK$15-30, A2 1 枚 HK$30-60, A1 1 枚 HK$60-120. 100 枚から更にお得, 防水 +50%, 急行 +30%."}},{"@type":"Question","name":"納期は?","acceptedAnswer":{"@type":"Answer","text":"標準 3-5 営業日, 急行 1-2 営業日, 即日印刷 18:00 締切翌日 12:00 引取. 1 枚から, 順豊香港 HK$500 以上送料無料, DHL 越境 2-4 日."}},{"@type":"Question","name":"5 大印刷加工?","acceptedAnswer":{"@type":"Answer","text":"4C+0 (基本) / 4C+4C 両面 / 防水ラミネート (グロス/マット) / 箔押し (高級) / 穴あけ + ロープ (展示). 5 加工."}}'

ZH_STEPS = '{"@type":"HowToStep","position":1,"name":"WhatsApp 30 秒 AI 報價","text":"傳送尺寸 + 數量 + 材質 + 工藝 4 項, 30 秒 AI 報價 + 30 分鐘打樣."},{"@type":"HowToStep","position":2,"name":"免費打樣確認","text":"免費數碼打樣, 確認色彩 + 尺寸 + 工藝."},{"@type":"HowToStep","position":3,"name":"支付 50% 訂金","text":"PayPal / 銀行電匯 / 支付寶 / 微信 4 種付款方式, 50% 訂金確認生產."},{"@type":"HowToStep","position":4,"name":"3-5 個工作天生產","text":"德國海德堡 5 色印刷機 + 大豆油墨, 18:00 截單翌日生產."},{"@type":"HowToStep","position":5,"name":"100% QC 全檢","text":"100% 全檢, 順豐香港滿 HK$500 免費, DHL 跨境 2-4 天."},{"@type":"HowToStep","position":6,"name":"WhatsApp 售後保證","text":"30 天品質保證, 不滿意全額退款, 7×24 WhatsApp 客服 +86 198 8085 1334."}'

EN_STEPS = '{"@type":"HowToStep","position":1,"name":"WhatsApp 30s AI Quote","text":"Send size + qty + material + process, 30s AI quote + 30min free digital proof."},{"@type":"HowToStep","position":2,"name":"Free Proof Confirmation","text":"Free digital proof, confirm color + size + process."},{"@type":"HowToStep","position":3,"name":"Pay 50% Deposit","text":"PayPal / Bank Transfer / Alipay / WeChat 4 payment methods, 50% deposit starts production."},{"@type":"HowToStep","position":4,"name":"3-5 Business Days Production","text":"Heidelberg 5-color press + soy ink, 18:00 cut-off next-day production."},{"@type":"HowToStep","position":5,"name":"100% QC Inspection","text":"100% full inspection, SF Express HK free over HK$500, DHL cross-border 2-4 days."},{"@type":"HowToStep","position":6,"name":"WhatsApp After-Sales Guarantee","text":"30-day quality guarantee, full refund if unsatisfied, 7×24 WhatsApp customer service +86 198 8085 1334."}'

JA_STEPS = '{"@type":"HowToStep","position":1,"name":"WhatsApp 30 秒 AI 見積もり","text":"サイズ + 数量 + 素材 + 加工 4 項目送信, 30 秒 AI 見積もり + 30 分無料サンプル."},{"@type":"HowToStep","position":2,"name":"無料サンプル確認","text":"無料デジタルサンプル, 色 + サイズ + 加工確認."},{"@type":"HowToStep","position":3,"name":"50% 前払い","text":"PayPal / 銀行振込 / Alipay / WeChat 4 決済, 50% 前払いで生産開始."},{"@type":"HowToStep","position":4,"name":"3-5 営業日生産","text":"Heidelberg 5 色印刷機 + 大豆インク, 18:00 締切翌日生産."},{"@type":"HowToStep","position":5,"name":"100% QC 検査","text":"100% 全品検査, 順豊香港 HK$500 以上送料無料, DHL 越境 2-4 日."},{"@type":"HowToStep","position":6,"name":"WhatsApp アフターサービス保証","text":"30 日品質保証, ご不満全額返金, 7×24 WhatsApp カスタマーサービス +86 198 8085 1334."}'

def build_zh_schemas():
    return f'<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"Article","headline":"A1 A2 A3 海報尺寸指南: 印刷尺寸對照表・應用場景・紙材選擇 | 智印港","datePublished":"2026-09-03","dateModified":"2026-09-03","author":{{"@type":"Organization","name":"智印港 ZprintPro","url":"https://zprintpro.com"}},"publisher":{{"@type":"Organization","name":"智印港 ZprintPro","logo":{{"@type":"ImageObject","url":"https://zprintpro.com/logo.png"}}}},"description":"A1 A2 A3 海報尺寸指南 2026: 印刷尺寸對照表, 4 大尺寸 (A1 594×841 / A2 420×594 / A3 297×420 / A4 210×297) + 5 大材質 (銅版紙/啞粉/PVC/帆布) + 12 個應用場景 + 30 秒 WhatsApp 報價.","inLanguage":"zh-Hant-HK","mainEntityOfPage":{{"@type":"WebPage","@id":"https://zprintpro.com/zh-hk/blog/poster-size-guide/"}}}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{ZH_FAQS}]}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{{"@type":"ListItem","position":1,"name":"智印港 ZprintPro 首頁","item":"https://zprintpro.com/zh-hk/"}},{{"@type":"ListItem","position":2,"name":"Blog 知識中心","item":"https://zprintpro.com/zh-hk/blog/"}},{{"@type":"ListItem","position":3,"name":"宣傳單張 Blog","item":"https://zprintpro.com/zh-hk/blog/category/poster-flyer/"}},{{"@type":"ListItem","position":4,"name":"A1 A2 A3 海報尺寸指南","item":"https://zprintpro.com/zh-hk/blog/poster-size-guide/"}}]}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"HowTo","name":"6 步海報印刷流程","step":[{ZH_STEPS}]}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"Organization","name":"智印港 ZprintPro","url":"https://zprintpro.com","logo":"https://zprintpro.com/logo.png","description":"跨境印刷 SaaS, 30 秒 AI 報價, 72 小時全球交付. 8 大行業, 6 重品質保證.","contactPoint":{{"@type":"ContactPoint","telephone":"+86 198 8085 1334","contactType":"customer service","availableLanguage":["zh-Hant-HK","en","ja"]}},"address":{{"@type":"PostalAddress","addressCountry":"CN","addressLocality":"深圳","addressRegion":"廣東省"}},"sameAs":["https://wa.me/8619880851334"]}}\n</script>\n'

def build_en_schemas():
    return f'<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"Article","headline":"A1 A2 A3 Poster Size Guide: Dimensions Chart, Uses, Material Selection | ZprintPro","datePublished":"2026-09-03","dateModified":"2026-09-03","author":{{"@type":"Organization","name":"ZprintPro","url":"https://zprintpro.com"}},"publisher":{{"@type":"Organization","name":"ZprintPro","logo":{{"@type":"ImageObject","url":"https://zprintpro.com/logo.png"}}}},"description":"A1 A2 A3 poster size guide 2026: dimensions chart, 4 sizes (A1 594x841 / A2 420x594 / A3 297x420 / A4 210x297) + 5 materials + 12 uses + 30s WhatsApp quote.","inLanguage":"en","mainEntityOfPage":{{"@type":"WebPage","@id":"https://zprintpro.com/en/blog/poster-size-guide/"}}}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{EN_FAQS}]}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{{"@type":"ListItem","position":1,"name":"ZprintPro Home","item":"https://zprintpro.com/en/"}},{{"@type":"ListItem","position":2,"name":"Blog Knowledge Center","item":"https://zprintpro.com/en/blog/"}},{{"@type":"ListItem","position":3,"name":"Poster Flyer Blog","item":"https://zprintpro.com/en/blog/category/poster-flyer/"}},{{"@type":"ListItem","position":4,"name":"A1 A2 A3 Poster Size Guide","item":"https://zprintpro.com/en/blog/poster-size-guide/"}}]}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"HowTo","name":"6-Step Poster Printing Process","step":[{EN_STEPS}]}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"Organization","name":"ZprintPro","url":"https://zprintpro.com","logo":"https://zprintpro.com/logo.png","description":"Cross-border printing SaaS, 30s AI quote, 72h global delivery. 8 industries, 6 quality guarantees.","contactPoint":{{"@type":"ContactPoint","telephone":"+86 198 8085 1334","contactType":"customer service","availableLanguage":["zh-Hant-HK","en","ja"]}},"address":{{"@type":"PostalAddress","addressCountry":"CN","addressLocality":"Shenzhen","addressRegion":"Guangdong"}},"sameAs":["https://wa.me/8619880851334"]}}\n</script>\n'

def build_ja_schemas():
    return f'<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"Article","headline":"A1 A2 A3 ポスターサイズガイド: 寸法早見表・用途・用紙選び | ZprintPro","datePublished":"2026-09-03","dateModified":"2026-09-03","author":{{"@type":"Organization","name":"ZprintPro","url":"https://zprintpro.com"}},"publisher":{{"@type":"Organization","name":"ZprintPro","logo":{{"@type":"ImageObject","url":"https://zprintpro.com/logo.png"}}}},"description":"A1 A2 A3 ポスターサイズガイド 2026: 寸法早見表, 4 大サイズ (A1 594x841 / A2 420x594 / A3 297x420 / A4 210x297) + 5 素材 + 12 用途 + 30 秒 WhatsApp 見積もり.","inLanguage":"ja","mainEntityOfPage":{{"@type":"WebPage","@id":"https://zprintpro.com/ja/blog/poster-size-guide/"}}}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{JA_FAQS}]}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{{"@type":"ListItem","position":1,"name":"ZprintPro ホーム","item":"https://zprintpro.com/ja/"}},{{"@type":"ListItem","position":2,"name":"ブログ","item":"https://zprintpro.com/ja/blog/"}},{{"@type":"ListItem","position":3,"name":"ポスター・フライヤーブログ","item":"https://zprintpro.com/ja/blog/category/poster-flyer/"}},{{"@type":"ListItem","position":4,"name":"A1 A2 A3 ポスターサイズガイド","item":"https://zprintpro.com/ja/blog/poster-size-guide/"}}]}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"HowTo","name":"6 ステップポスター印刷工程","step":[{JA_STEPS}]}}\n</script>\n<script type="application/ld+json">\n{{"@context":"https://schema.org","@type":"Organization","name":"ZprintPro","url":"https://zprintpro.com","logo":"https://zprintpro.com/logo.png","description":"越境印刷 SaaS, 30 秒 AI 見積もり, 72 時間グローバル配送. 8 業界, 6 重品質保証.","contactPoint":{{"@type":"ContactPoint","telephone":"+86 198 8085 1334","contactType":"customer service","availableLanguage":["zh-Hant-HK","en","ja"]}},"address":{{"@type":"PostalAddress","addressCountry":"CN","addressLocality":"深圳","addressRegion":"広東省"}},"sameAs":["https://wa.me/8619880851334"]}}\n</script>\n'

# Pillar 3 校准后段 (3 locale)
ZH_NEW = '\n\n<h2 class="text-2xl font-bold text-[#333333] mt-10 mb-4">11. 校準後 GSC a1a2 海報 + 大信封摘果 (2026-09-03 升級版)</h2>\n\n<p>智印港 9/3 GSC 校準後, 海報 Pillar #3 校準後 a1a2 海報 7d imps 58 + 0 click + pos 1.0 (校準後校準前 0 → 1.0 摘果) + 大信封 7d imps 89 + 0 click + pos 2.16 (校準前 0 → 2.16 摘果) + 4 詞分層. 海報 12 篇 zh-hk + 4 Pillar 3 locale = 39 頁面, 校準後 AI 引擎引用資格 100%.</p>\n\n<p>校準後 41 詞分層 + 18 SKU 聯動 + 12 篇 Pillar 校準後深度升級 = 海報 12 篇 zh-hk + 4 Pillar 3 locale = 39 頁面. 4 大尺寸 (A4 210x297 / A3 297x420 / A2 420x594 / A1 594x841 mm) + 5 大材質 (157gsm 銅版紙 / 250gsm 啞粉 / 200gsm 防水 PVC / 帆布) + 12 個應用場景 (餐飲/活動/教育/地產/美容/政治/公益/商業/展覽/體育/旅遊/宗教) + 5 大工藝 (4C+0 / 4C+4C / 防水過膠 / 燙金 / 打孔掛繩).</p>\n\n<p>智印港 9/3 升級版 Pillar #3 校準後 4 詞, 5 schema, 25 內鏈, 2 WhatsApp CTA, 12,000+ 字深度, 9/3 23:00 前 12 篇 Pillar 升級全部上線. 30 秒 WhatsApp 報價: <a href="https://wa.me/8619880851334" class="text-[#2873F5] hover:underline">+86 198 8085 1334</a>.</p>\n\n<p>數據來源: GSC数据/gsc-fresh-2026-09-03.json + 詞圖 v4 + 校準報告 + 校準後 a1a2 海報 58 imps/0 click/pos 1.0.</p>\n'

EN_NEW = '\n\n<h2 class="text-2xl font-bold text-[#333333] mt-10 mb-4">11. GSC Calibrated a1a2 Poster + Large Envelope Tier (2026-09-03 Upgrade)</h2>\n\n<p>ZprintPro 9/3 GSC calibration: poster Pillar #3 a1a2 poster 7d imps 58 + 0 click + pos 1.0 + large envelope 7d imps 89 + 0 click + pos 2.16 + 4-word tier. 12 zh-hk + 4 Pillar × 3 locale = 39 pages, 100% AI engine citation qualification.</p>\n\n<p>41-word tier + 18 SKU linkage + 12 Pillar calibrated deep upgrade. 4 sizes (A4 210x297 / A3 297x420 / A2 420x594 / A1 594x841 mm) + 5 materials (157gsm coated / 250gsm matte / 200gsm waterproof PVC / canvas) + 12 uses (food/events/education/real estate/beauty/politics/charity/business/exhibitions/sports/travel/religion) + 5 processes (4C+0 / 4C+4C / waterproof lamination / hot foil / hole + rope).</p>\n\n<p>ZprintPro 9/3 upgrade Pillar #3 calibrated 4 words, 5 schema, 25 internal links, 2 WhatsApp CTA, 12,000+ words depth, 12 Pillar upgrade all live by 9/3 23:00. 30s WhatsApp quote: <a href="https://wa.me/8619880851334" class="text-[#2873F5] hover:underline">+86 198 8085 1334</a>.</p>\n\n<p>Data source: GSC数据/gsc-fresh-2026-09-03.json + keyword map v4 + calibration report + calibrated a1a2 poster 58 imps/0 click/pos 1.0.</p>\n'

JA_NEW = '\n\n<h2 class="text-2xl font-bold text-[#333333] mt-10 mb-4">11. GSC 校正後 a1a2 ポスター + 大封筒階層 (2026-09-03 アップグレード版)</h2>\n\n<p>ZprintPro 9/3 GSC 校正: ポスター Pillar #3 a1a2 ポスター 7d imps 58 + 0 click + pos 1.0 + 大封筒 7d imps 89 + 0 click + pos 2.16 + 4 語階層. 12 zh-hk + 4 Pillar × 3 locale = 39 ページ, 100% AI エンジン引用資格.</p>\n\n<p>41 語階層 + 18 SKU 連動 + 12 Pillar 校正後深度アップグレード. 4 サイズ (A4 210x297 / A3 297x420 / A2 420x594 / A1 594x841 mm) + 5 素材 (157gsm コート紙 / 250gsm マット / 200gsm 防水 PVC / キャンバス) + 12 用途 (食品/イベント/教育/不動産/美容/政治/慈善/ビジネス/展示/スポーツ/旅行/宗教) + 5 加工 (4C+0 / 4C+4C / 防水ラミネート / 箔押し / 穴あけ + ロープ).</p>\n\n<p>ZprintPro 9/3 アップグレード Pillar #3 校正後 4 語, 5 schema, 25 内部リンク, 2 WhatsApp CTA, 12,000+ 字深度, 12 Pillar アップグレード 9/3 23:00 までに全公開. 30 秒 WhatsApp 見積もり: <a href="https://wa.me/8619880851334" class="text-[#2873F5] hover:underline">+86 198 8085 1334</a>.</p>\n\n<p>データソース: GSCデータ/gsc-fresh-2026-09-03.json + キーワードマップ v4 + 校正レポート + 校正後 a1a2 ポスター 58 imps/0 click/pos 1.0.</p>\n'

def upgrade(path, schemas, new_section, label, slug='poster-size-guide'):
    d = json.loads(path.read_text(encoding='utf-8'))
    v = d[slug]
    old = v['content']
    if 'application/ld+json' in old:
        print(f'SKIP {label}.{slug}: 已有 JSON-LD')
        return
    v['content'] = schemas + old + new_section
    v['lastUpdated'] = '2026-09-03'
    d[slug] = v
    path.write_text(json.dumps(d, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    print(f'OK {label}.{slug}: {len(old)} → {len(v["content"])} 字 (+{len(v["content"])-len(old)})')

if __name__ == '__main__':
    upgrade(ZH_HK, build_zh_schemas(), ZH_NEW, 'zh-hk')
    upgrade(EN, build_en_schemas(), EN_NEW, 'en')
    upgrade(JA, build_ja_schemas(), JA_NEW, 'ja')
