var fs = require('fs');
var page = fs.readFileSync('F:/zprintpro-nextjs/src/app/[locale]/product/[slug]/page.tsx', 'utf-8');

// Import getUnitPriceAnchor
page = page.replace(
  "import { convertPriceRangeString, convertToFromPrice } from '@/lib/pricing';",
  "import { convertPriceRangeString, convertToFromPrice, getUnitPriceAnchor } from '@/lib/pricing';"
);

// Replace price display block
var oldBlock = '              {/* 价格显示 \u2014 去色块简洁风格 */}\n              <div className="mb-5">\n                <div className="flex items-baseline gap-2 mb-1 flex-wrap">\n                  <span className="text-[33px] font-extrabold text-[#F87314] leading-tight">\n                    {convertToFromPrice(product.price_range, locale, product.category_slug, product.slug)}\n                  </span>\n                  <span className="text-sm text-gray-400">\n                    {locale === \'zh-hk\' ? \'\u8d77\' : locale === \'en\' ? \'From\' : \'\u301c\'}\n                  </span>\n                  <span className="text-xs text-gray-400 ml-1">\n                    {locale === \'zh-hk\' ? `\u5b8c\u6574\u50f9\u683c ${product.price_range}` : locale === \'en\' ? `Full price: ${convertPriceRangeString(product.price_range, locale, product.category_slug, product.slug)}` : `\u4fa1\u683c ${convertPriceRangeString(product.price_range, locale, product.category_slug, product.slug)}`}\n                  </span>\n                </div>\n                {locale !== \'zh-hk\' && (\n                  <div className="flex items-center gap-1.5 mb-2">\n                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-semibold bg-green-100 text-green-800 border border-green-200">\n                      <svg className="w-3 h-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7"/></svg>\n                      {locale === \'en\' ? \'Free International Shipping\' : \'SF Express \\u00b7 \\u914d\\u9001\\u6599\\u5b9f\\u8cbb\'}\n                    </span>\n                    <span className="text-xs text-gray-400">{locale === \'en\' ? \'DHL/FedEx 3-5 days to USA, 2-4 days to Japan\' : \'DHL/FedEx \\u30a2\\u30e1\\u30ea\\u30ab3-5\\u65e5\\u3001\\u65e5\\u672c2-4\\u65e5\'}</span>\n                  </div>\n                )}';

var newBlock = '              {/* v18: 单价优先价格锚 */}\n              <div className="mb-5">\n                {(() => {\n                  const ua = getUnitPriceAnchor(product.slug, locale);\n                  if (ua) {\n                    return (\n                      <div>\n                        <div className="flex items-baseline gap-2 mb-1 flex-wrap">\n                          <span className="text-[33px] font-extrabold text-[#F87314] leading-tight">\n                            {ua.display}\n                          </span>\n                          <span className="text-lg font-semibold text-gray-700">\n                            {ua.unitLabel} {locale === \'zh-hk\' ? \'\u8d77\' : locale === \'en\' ? \'from\' : \'\u304b\u3089\'}\n                          </span>\n                        </div>\n                        <p className="text-xs text-gray-400">\n                          {ua.qty.toLocaleString()} {locale===\'ja\'?\'\u500b\':\'\u500b\'}\u8d77\u6279 \\u00b7 {locale===\'ja\'?\'\u30ed\u30c3\u30c8\\u00a5\':\'\\u6574\\u6279 HK$\'}{ua.batchPrice.toLocaleString()} {locale===\'zh-hk\'?\'\u8d77\':locale===\'en\'?\'from\':\'\u304b\u3089\'}\n                        </p>\n                      </div>\n                    );\n                  }\n                  return (\n                    <div>\n                      <div className="flex items-baseline gap-2 mb-1 flex-wrap">\n                        <span className="text-[33px] font-extrabold text-[#F87314] leading-tight">\n                          {convertToFromPrice(product.price_range, locale, product.category_slug, product.slug)}\n                        </span>\n                        <span className="text-sm text-gray-400">\n                          {locale === \'zh-hk\' ? \'\u8d77\' : locale === \'en\' ? \'From\' : \'\u301c\'}\n                        </span>\n                      </div>\n                    </div>\n                  );\n                })()}\n              </div>';

page = page.replace(oldBlock, newBlock);
fs.writeFileSync('F:/zprintpro-nextjs/src/app/[locale]/product/[slug]/page.tsx', page, 'utf-8');
console.log('PDP unit-price anchor applied');
